services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      API_URL: http://localhost:8000
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_NAME: tienda_cloud
      APP_PAGOS_URL: http://app-pagos:8002
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      app-pagos:
        condition: service_started

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tienda_cloud
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  app-pagos:
    build:
      context: ./app-pagos
      dockerfile: Dockerfile
    container_name: app-pagos
    environment:
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN}
      MP_PUBLIC_KEY: ${MP_PUBLIC_KEY}
      MP_WEBHOOK_URL: ${MP_WEBHOOK_URL}
      MP_SUCCESS_URL: ${MP_SUCCESS_URL}
      MP_FAILURE_URL: ${MP_FAILURE_URL}
      MP_PENDING_URL: ${MP_PENDING_URL}
    ports:
      - "8002:8002"
    restart: unless-stopped

volumes:
  mysql_data:
